import pyautogui as g
from time import sleep


sleep(3)
g.write("1")
g.press("return")
g.write("12345678")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("1")
g.press("return")

g.write("1")
g.press("return")
g.write("23456789")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("1")
g.press("return")


g.write("1")
g.press("return")
g.write("34567890")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("2")
g.press("return")

g.write("1")
g.press("return")
g.write("45678901")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("56789012")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("67890123")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("78901234")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("4")
g.press("return")

g.write("1")
g.press("return")
g.write("89012345")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("4")
g.press("return")

#--------------------------------------------------------------------------------------------------------

g.write("2")
g.press("return")
g.write("overwacho")
g.press("return")
g.write("123")
g.press("return")
g.write("12345678")
g.press("return")
g.write("23456789")
g.press("return")
g.write("3456789099999")
g.press("return")
g.write("45678901")
g.press("return")
g.write("56789012")
g.press("return")
g.write("67890123")
g.press("return")
g.write("78901234")
g.press("return")
g.write("89012345")
g.press("return")
g.write("0")
g.press("return")