import pyautogui as g
from time import sleep


sleep(3)
g.write("clear")
g.press("return")
g.write("python3 menu.py")
g.press("return")
g.write("1")
g.press("return")
g.write("12345678")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("1")
g.press("return")

g.write("1")
g.press("return")
g.write("23456789")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("1")
g.press("return")


g.write("1")
g.press("return")
g.write("34567890")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("2")
g.press("return")

g.write("1")
g.press("return")
g.write("45678901")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("56789012")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("67890123")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("78901234")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("4")
g.press("return")

g.write("1")
g.press("return")
g.write("89012345")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("4")
g.press("return")

#primer juego
#--------------------------------------------------------------------------------------------------------

g.write("2")
g.press("return")
g.write("overwacho")
g.press("return")
g.write("123")
g.press("return")
g.write("12345678")
g.press("return")
g.write("23456789") 
g.press("return")
g.write("34567890")
g.press("return")
g.write("45678901")
g.press("return")
g.write("56789012")
g.press("return")
g.write("67890123")
g.press("return")
g.write("78901234")
g.press("return")
g.write("89012345")
g.press("return")
g.write("0")
g.press("return")

g.write("2")
g.press("return")
g.write("overwacho")
g.press("return")
g.write("123")
g.press("return")
g.write("12345678")
g.press("return")
g.write("23456789")
g.press("return")
g.write("34567890")
g.press("return")
g.write("45678901")
g.press("return")
g.write("56789012")
g.press("return")
g.write("67890123")
g.press("return")
g.write("78901234")
g.press("return")
g.write("89012345")
g.press("return")
g.write("0")
g.press("return")

#nueva lista de devs 2
#---------------------------------------------------------------------------------------



g.write("1")
g.press("return")
g.write("11111111")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("1")
g.press("return")

g.write("1")
g.press("return")
g.write("22222222")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("1")
g.press("return")


g.write("1")
g.press("return")
g.write("33333333")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("2")
g.press("return")

g.write("1")
g.press("return")
g.write("44444444")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("55555555")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("66666666")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("77777777")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("4")
g.press("return")

g.write("1")
g.press("return")
g.write("88888888")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("10")
g.press("return")
g.write("4")
g.press("return")

#segundo juego
#-------------------------------------

g.write("2")
g.press("return")
g.write("CYBERPUN")
g.press("return")
g.write("123")
g.press("return")
g.write("11111111")
g.press("return")
g.write("22222222")
g.press("return")
g.write("33333333")
g.press("return")
g.write("44444444")
g.press("return")
g.write("55555555")
g.press("return")
g.write("66666666")
g.press("return")
g.write("77777777")
g.press("return")
g.write("88888888")
g.press("return")
g.write("0")
g.press("return")


#nueva lista de devs 3
#---------------------------------------------------------------------------------------


g.write("1")
g.press("return")
g.write("11111112")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("5")
g.press("return")
g.write("1")
g.press("return")

g.write("1")
g.press("return")
g.write("22222223")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("7")
g.press("return")
g.write("1")
g.press("return")


g.write("1")
g.press("return")
g.write("33333334")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("4")
g.press("return")
g.write("2")
g.press("return")

g.write("1")
g.press("return")
g.write("44444445")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("4")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("55555556")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("8")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("66666667")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("2")
g.press("return")
g.write("3")
g.press("return")

g.write("1")
g.press("return")
g.write("77777778")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("1")
g.press("return")
g.write("4")
g.press("return")

g.write("1")
g.press("return")
g.write("88888889")
g.press("return")
g.write("agustin corujo")
g.press("return")
g.write("Uruguay")
g.press("return")
g.write("02/12/2002")
g.press("return")
g.write("10")
g.press("return")
g.write("4")
g.press("return")

#tercer juego
#-------------------------------------

g.write("2")
g.press("return")
g.write("LIG OF LELLEND")
g.press("return")
g.write("123")
g.press("return")
g.write("11111112")
g.press("return")
g.write("22222223")
g.press("return")
g.write("33333334")
g.press("return")
g.write("44444445")
g.press("return")
g.write("55555556")
g.press("return")
g.write("66666667")
g.press("return")
g.write("77777778")
g.press("return")
g.write("88888889")
g.press("return")
g.write("0")
g.press("return")

